# Generated by Django 3.0.7 on 2020-12-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CCS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faclogin',
            name='created',
        ),
        migrations.RemoveField(
            model_name='faclogin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='faclogin',
            name='name',
        ),
        migrations.AddField(
            model_name='faclogin',
            name='pwd',
            field=models.CharField(default=False, max_length=8),
        ),
        migrations.AddField(
            model_name='faclogin',
            name='userid',
            field=models.CharField(default=False, max_length=20),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
